name: Byran Zaugg
markdown: redcarpet
baseurl: "http://blzaugg.github.io/kovalcin"
exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME,
  svg,
  scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  readme.md
]

excerpt_separator: <!--more-->